export interface Language {
  code: string;
  name: string;
  nativeName: string;
  countryCode: string;
}

export const LANGUAGES: Language[] = [
  { code: 'en', name: 'English', nativeName: 'English', countryCode: 'US' },
  { code: 'es', name: 'Spanish', nativeName: 'Español', countryCode: 'ES' },
  { code: 'fr', name: 'French', nativeName: 'Français', countryCode: 'FR' },
  { code: 'de', name: 'German', nativeName: 'Deutsch', countryCode: 'DE' },
  { code: 'pt', name: 'Portuguese', nativeName: 'Português', countryCode: 'BR' },
  { code: 'ru', name: 'Russian', nativeName: 'Русский', countryCode: 'RU' },
  { code: 'ja', name: 'Japanese', nativeName: '日本語', countryCode: 'JP' },
  { code: 'ko', name: 'Korean', nativeName: '한국어', countryCode: 'KR' },
  { code: 'zh', name: 'Chinese (Simplified)', nativeName: '简体中文', countryCode: 'CN' },
  { code: 'ar', name: 'Arabic', nativeName: 'العربية', countryCode: 'SA' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', countryCode: 'IN' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', countryCode: 'BD' },
  { code: 'id', name: 'Indonesian', nativeName: 'Bahasa Indonesia', countryCode: 'ID' },
  { code: 'tr', name: 'Turkish', nativeName: 'Türkçe', countryCode: 'TR' },
  { code: 'vi', name: 'Vietnamese', nativeName: 'Tiếng Việt', countryCode: 'VN' },
  { code: 'th', name: 'Thai', nativeName: 'ภาษาไทย', countryCode: 'TH' },
  { code: 'it', name: 'Italian', nativeName: 'Italiano', countryCode: 'IT' },
  { code: 'pl', name: 'Polish', nativeName: 'Polski', countryCode: 'PL' },
  { code: 'uk', name: 'Ukrainian', nativeName: 'Українська', countryCode: 'UA' },
  { code: 'nl', name: 'Dutch', nativeName: 'Nederlands', countryCode: 'NL' },
  { code: 'sv', name: 'Swedish', nativeName: 'Svenska', countryCode: 'SE' },
  { code: 'fi', name: 'Finnish', nativeName: 'Suomi', countryCode: 'FI' },
  { code: 'no', name: 'Norwegian', nativeName: 'Norsk', countryCode: 'NO' },
  { code: 'da', name: 'Danish', nativeName: 'Dansk', countryCode: 'DK' },
  { code: 'cs', name: 'Czech', nativeName: 'Čeština', countryCode: 'CZ' },
  { code: 'ro', name: 'Romanian', nativeName: 'Română', countryCode: 'RO' },
  { code: 'hu', name: 'Hungarian', nativeName: 'Magyar', countryCode: 'HU' },
  { code: 'el', name: 'Greek', nativeName: 'Ελληνικά', countryCode: 'GR' },
  { code: 'he', name: 'Hebrew', nativeName: 'עברית', countryCode: 'IL' },
  { code: 'fa', name: 'Persian', nativeName: 'فارسی', countryCode: 'IR' },
  { code: 'ms', name: 'Malay', nativeName: 'Bahasa Melayu', countryCode: 'MY' },
  { code: 'sw', name: 'Swahili', nativeName: 'Kiswahili', countryCode: 'KE' },
  { code: 'tl', name: 'Filipino', nativeName: 'Filipino', countryCode: 'PH' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', countryCode: 'PK' },
  { code: 'sq', name: 'Albanian', nativeName: 'Shqip', countryCode: 'AL' },
  { code: 'am', name: 'Amharic', nativeName: 'አማርኛ', countryCode: 'ET' },
  { code: 'hy', name: 'Armenian', nativeName: 'Հայերեն', countryCode: 'AM' },
  { code: 'az', name: 'Azerbaijani', nativeName: 'Azərbaycan', countryCode: 'AZ' },
  { code: 'be', name: 'Belarusian', nativeName: 'Беларуская', countryCode: 'BY' },
  { code: 'bg', name: 'Bulgarian', nativeName: 'Български', countryCode: 'BG' },
  { code: 'ca', name: 'Catalan', nativeName: 'Català', countryCode: 'ES' },
  { code: 'hr', name: 'Croatian', nativeName: 'Hrvatski', countryCode: 'HR' },
  { code: 'sk', name: 'Slovak', nativeName: 'Slovenčina', countryCode: 'SK' },
  { code: 'sl', name: 'Slovenian', nativeName: 'Slovenščina', countryCode: 'SI' },
  { code: 'sr', name: 'Serbian', nativeName: 'Српски', countryCode: 'RS' },
  { code: 'mk', name: 'Macedonian', nativeName: 'Македонски', countryCode: 'MK' },
  { code: 'af', name: 'Afrikaans', nativeName: 'Afrikaans', countryCode: 'ZA' },
  { code: 'cy', name: 'Welsh', nativeName: 'Cymraeg', countryCode: 'GB' },
  { code: 'et', name: 'Estonian', nativeName: 'Eesti', countryCode: 'EE' },
  { code: 'eu', name: 'Basque', nativeName: 'Euskara', countryCode: 'ES' },
  { code: 'gl', name: 'Galician', nativeName: 'Galego', countryCode: 'ES' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', countryCode: 'IN' },
  { code: 'is', name: 'Icelandic', nativeName: 'Íslenska', countryCode: 'IS' },
  { code: 'ka', name: 'Georgian', nativeName: 'ქართული', countryCode: 'GE' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', countryCode: 'IN' },
  { code: 'lo', name: 'Lao', nativeName: 'ລາວ', countryCode: 'LA' },
  { code: 'lt', name: 'Lithuanian', nativeName: 'Lietuvių', countryCode: 'LT' },
  { code: 'lv', name: 'Latvian', nativeName: 'Latviešu', countryCode: 'LV' },
  { code: 'mn', name: 'Mongolian', nativeName: 'Монгол', countryCode: 'MN' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', countryCode: 'IN' },
  { code: 'mt', name: 'Maltese', nativeName: 'Malti', countryCode: 'MT' },
  { code: 'ne', name: 'Nepali', nativeName: 'नेपाली', countryCode: 'NP' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', countryCode: 'IN' },
];

export function getLanguageByCode(code: string): Language | undefined {
  return LANGUAGES.find((l) => l.code === code);
}
