export const VOICE_TEST_PHRASES: Record<string, string> = {
  en: 'Language is unbounded',
  es: 'El lenguaje es ilimitado',
  fr: 'Le langage est sans limites',
  de: 'Sprache ist grenzenlos',
  pt: 'A linguagem é ilimitada',
  ru: 'Язык не имеет границ',
  ja: '言語に境界はない',
  ko: '언어에는 경계가 없다',
  zh: '语言是无边界的',
  ar: 'اللغة بلا حدود',
  hi: 'भाषा असीमित है',
  bn: 'ভাষা হোক সর্বদা উন্মুক্ত',
  id: 'Bahasa itu tak terbatas',
  tr: 'Dil sınırsızdır',
  vi: 'Ngôn ngữ là vô hạn',
  th: 'ภาษาไม่มีขอบเขต',
  it: 'Il linguaggio è illimitato',
  pl: 'Język jest nieograniczony',
  uk: 'Мова безмежна',
  nl: 'Taal is grenzeloos',
  sv: 'Språket är obegränsat',
  fi: 'Kieli on rajaton',
  no: 'Språket er ubegrenset',
  da: 'Sproget er ubegrænset',
  cs: 'Jazyk je neomezený',
  ro: 'Limbajul este nelimitat',
  hu: 'A nyelv határtalan',
  el: 'Η γλώσσα είναι αχανής',
  he: 'השפה היא בלתי מוגבלת',
  fa: 'زبان بی‌حد است',
  ms: 'Bahasa tidak terbatas',
  sw: 'Lugha haina mipaka',
  tl: 'Ang wika ay walang hangganan',
  ur: 'زبان لامحدود ہے',
  sq: 'Gjuha është e pakufizuar',
  am: 'ቋንቋ ወሰን የለውም',
  hy: 'Լեզուն անսահման է',
  az: 'Dil hədsizdir',
  be: 'Мова не мае мяжы',
  bg: 'Езикът е безграничен',
  ca: 'El llenguatge és il·limitat',
  hr: 'Jezik je neograničen',
  sk: 'Jazyk je neobmedzený',
  sl: 'Jezik je neomejen',
  sr: 'Језик је неограничен',
  mk: 'Јазикот е неограничен',
};

export function getTestPhrase(languageCode: string): string {
  return VOICE_TEST_PHRASES[languageCode] || VOICE_TEST_PHRASES['en'];
}
